services:
  db:
    image: postgres
    container_name: db-sql
    ports:
      - 5432:5432
    env_file:
      - ./.env
    volumes:
      - ./volume-postgres:/var/lib/postgresql/data
  db-ui:
    image: adminer
    container_name: adminer
    ports:
    - 8080:8080
    env_file:
      - ./.env
    depends_on:
      - db
